export const SAVE_PHONE_NUMBER_VERIFY ='SAVE_PHONE_NUMBER_VERIFY'
export const SAVE_PHONE_NUMBER_VERIFY_SUCCESS ='SAVE_PHONE_NUMBER_VERIFY_SUCCESS'
export const SAVE_PHONE_NUMBER_VERIFY_FAIL ='SAVE_PHONE_NUMBER_VERIFY_FAIL'

export const RESEND_PHONE_VERIFICATION_CODE ='RESEND_PHONE_VERIFICATION_CODE'
export const RESEND_PHONE_VERIFICATION_CODE_SUCCESS ='RESEND_PHONE_VERIFICATION_CODE_SUCCESS'
export const RESEND_PHONE_VERIFICATION_CODE_FAIL ='RESEND_PHONE_VERIFICATION_CODE_FAIL'

export const VALIDATE_PHONE_NUMBER = 'VALIDATE_PHONE_NUMBER'
export const VALIDATE_PHONE_NUMBER_FAIL = 'VALIDATE_PHONE_NUMBER_FAIL'
export const VALIDATE_PHONE_NUMBER_SUCCESS = 'VALIDATE_PHONE_NUMBER_SUCCESS'

export const RESET_PHONE_STATE = 'RESET_PHONE_STATE'