export const AUTHENTICATION = "AUTHENTICATION";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";

export const RESEND_AUTHENTICATION_CODE = "RESEND_AUTHENTICATION_CODE";
export const RESEND_AUTHENTICATION_AUTHENTICATION_CODE_SUCCESS = "RESEND_AUTHENTICATION_AUTHENTICATION_CODE_SUCCESS";
export const RESEND_AUTHENTICATION_CODE_FAILURE = "RESEND_AUTHENTICATION_CODE_FAILURE";
export const LOGOUT_AUTH_DISABLE = "LOGOUT_AUTH_DISABLE";