export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const USER_LOGOUT = 'USER_LOGOUT';

export const ACTIVATION = "ACTIVATION";
export const ACTIVATION_FAILURE = "ACTIVATION_FAILURE";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const RESEND_ACTIVATION_ACTIVATION_CODE_SUCCESS = 'RESEND_ACTIVATION_ACTIVATION_CODE_SUCCESS';
export const RESEND_ACTIVATION_CODE = 'RESEND_ACTIVATION_CODE';
export const RESEND_ACTIVATION_CODE_FAILURE = 'RESEND_ACTIVATION_CODE_FAILURE';
export const DISABLE_ACTIVATION_STATUS = 'DISABLE_ACTIVATION_STATUS';