export const GET_ALL_TYPE_OF_USER = "GET_ALL_TYPE_OF_USER"
export const GET_ALL_TYPE_OF_USER_SUCCESS = "GET_ALL_TYPE_OF_USER_SUCCESS"
export const GET_ALL_TYPE_OF_USER_FAIL = "GET_ALL_TYPE_OF_USER_FAIL"


export const ADD_NEW_TYPE_OF_USER = "ADD_ALL_TYPE_OF_USER"
export const ADD_NEW_TYPE_OF_USER_SUCCESS = "ADD_NEW_TYPE_OF_USER_SUCCESS"
export const ADD_NEW_TYPE_OF_USER_FAIL = "ADD_NEW_TYPE_OF_USER_FAIL"

export const RESET_TYPE_OF_USER_STATE = "RESET_TYPE_OF_USER_STATE"