export const GET_ALL_ROLES = "GET_ALL_ROLES"
export const GET_ALL_ROLES_SUCCESS = "GET_ALL_ROLES_SUCCESS"
export const GET_ALL_ROLES_FAIL = "GET_ALL_ROLES_FAIL"


export const ADD_NEW_ROLES = "ADD_ALL_ROLES"
export const ADD_NEW_ROLES_SUCCESS = "ADD_NEW_ROLES_SUCCESS"
export const ADD_NEW_ROLES_FAIL = "ADD_NEW_ROLES_FAIL"