export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const USER_LOGOUT = 'USER_LOGOUT';
export const UPDATE_LOGIN_SUCCESS = 'UPDATE_LOGIN_SUCCESS';