export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const UPDATE_LOGIN_SUCCESS = 'UPDATE_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';
export const CHANGE_AUTHENTICATION_STATUS = 'CHANGE_AUTHENTICATION_STATUS';


export const AUTHENTICATION = "AUTHENTICATION";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";

export const RESEND_AUTHENTICATION_CODE = "RESEND_AUTHENTICATION_CODE";
export const RESEND_AUTHENTICATION_AUTHENTICATION_CODE_SUCCESS = "RESEND_AUTHENTICATION_AUTHENTICATION_CODE_SUCCESS";
export const RESEND_AUTHENTICATION_CODE_FAILURE = "RESEND_AUTHENTICATION_CODE_FAILURE";
export const LOGOUT_AUTH_DISABLE = "LOGOUT_AUTH_DISABLE";
export const ACCOUNT_ACTIVATION_SWITCH = "ACCOUNT_ACTIVATION_SWITCH";