export const GET_ALL_PRIVILEDGES = "GET_ALL_PRIVILEDGES"
export const GET_ALL_PRIVILEDGES_SUCCESS = "GET_ALL_PRIVILEDGES_SUCCESS"
export const GET_ALL_PRIVILEDGES_FAIL = "GET_ALL_PRIVILEDGES_FAIL"

export const UPDATE_PRIVILEDGES = "UPDATE_PRIVILEDGES"
export const UPDATE_PRIVILEDGES_SUCCESS = "UPDATE_PRIVILEDGES_SUCCESS"
export const UPDATE_PRIVILEDGES_FAIL = "UPDATE_PRIVILEDGES_FAIL"

export const RESET_PRIVILEDGES_STATE = "RESET_PRIVILEDGES_STATE"