export const GET_CURRENCY = "GET_CURRENCY";
export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS";
export const GET_CURRENCY_FAILURE = "GET_CURRENCY_FAILURE";

export const CHOOSE_CURRENCY = "CHOOSE_CURRENCY";
export const CHOOSE_CURRENCY_SUCCESS = "CHOOSE_CURRENCY_SUCCESS";
export const CHOOSE_CURRENCY_FAILURE = "CHOOSE_CURRENCY_FAILURE";

export const CHANGE_SELECTED_CURRENCY = "CHANGE_SELECTED_CURRENCY";