export const VERIFY_EMAIL_LOADING = 'VERIFY_EMAIL_LOADING';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

export const VERIFY_EMAIL_TOKEN_LOADING = 'VERIFY_EMAIL_TOKEN_LOADING';
export const VERIFY_EMAIL_TOKEN_SUCCESS = 'VERIFY_EMAIL_TOKEN_SUCCESS';
export const VERIFY_EMAIL_TOKEN_FAILURE = 'VERIFY_EMAIL_TOKEN_FAILURE';

export const VERIFY_PHONE_LOADING = 'VERIFY_PHONE_LOADING';
export const VERIFY_PHONE_SUCCESS = 'VERIFY_PHONE_SUCCESS';
export const VERIFY_PHONE_FAILURE = 'VERIFY_PHONE_FAILURE';

export const VERIFY_PHONE_TOKEN_LOADING = 'VERIFY_PHONE_TOKEN_LOADING';
export const VERIFY_PHONE_TOKEN_SUCCESS = 'VERIFY_PHONE_TOKEN_SUCCESS';
export const VERIFY_PHONE_TOKEN_FAILURE = 'VERIFY_PHONE_TOKEN_FAILURE';

export const RESET_TWO_FACTOR_DEATIVATION_STATE = 'RESET_TWO_FACTOR_DEATIVATION_STATE';

export const RESEND_TOKEN_TO_EMAIL_FAILURE = 'RESEND_TOKEN_TO_EMAIL_FAILURE';
export const RESEND_TOKEN_TO_EMAIL_SUCCESS = 'RESEND_TOKEN_TO_EMAIL_SUCCESS';
export const RESEND_TOKEN_TO_EMAIL_LOADING = 'RESEND_TOKEN_TO_EMAIL_LOADING';