export const ACTIVATION = "ACTIVATION";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAILURE = "ACTIVATION_FAILURE";

export const RESEND_ACTIVATION_CODE = "RESEND_ACTIVATION_CODE";
export const RESEND_ACTIVATION_ACTIVATION_CODE_SUCCESS = "RESEND_ACTIVATION_ACTIVATION_CODE_SUCCESS";
export const RESEND_ACTIVATION_CODE_FAILURE = "RESEND_ACTIVATION_CODE_FAILURE";
export const LOGOUT_ACTIVATION_DISABLE = "LOGOUT_ACTIVATION_DISABLE";