export const ACTIVATE_TWOFACTOR = 'ACTIVATE_TWOFACTOR'
export const ACTIVATE_TWOFACTOR_SUCCESS = 'ACTIVATE_TWOFACTOR_SUCCESS'
export const ACTIVATE_TWOFACTOR_FAILURE = 'ACTIVATE_TWOFACTOR_FAILURE'

export const FINALISE_TWOFACTOR = 'FINALISE_TWOFACTOR'
export const FINALISE_TWOFACTOR_SUCCESS = 'FINALISE_TWOFACTOR_SUCCESS'
export const FINALISE_TWOFACTOR_FAILURE = 'FINALISE_TWOFACTOR_FAILURE'

export const DEACTIVATE_TWOFACTOR = 'DEACTIVATE_TWOFACTOR'
export const DEACTIVATE_TWOFACTOR_SUCCESS = 'DEACTIVATE_TWOFACTOR_SUCCESS'
export const DEACTIVATE_TWOFACTOR_FAILURE = 'DEACTIVATE_TWOFACTOR_FAILURE'