export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';

export const SELECT_ONE_USER = 'SELECT_ONE_USER';
export const SELECT_ONE_USER_SUCCESS = 'SELECT_ONE_USER_SUCCESS';
export const SELECT_ONE_USER_FAIL = 'SELECT_ONE_USER_FAIL';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const RESET_USERS_STATE = 'RESET_USERS_STATE';

export const REVERSE_DELETE_USER = 'REVERSE_DELETE_USER';
export const REVERSE_DELETE_USER_SUCCESS = 'REVERSE_DELETE_USER_SUCCESS';
export const REVERSE_DELETE_USER_FAIL = 'REVERSE_DELETE_USER_FAIL';

export const MANAGE_USER = 'MANAGE_USER';
export const MANAGE_USER_SUCCESS = 'MANAGE_USER_SUCCESS';
export const MANAGE_USER_FAIL = 'MANAGE_USER_FAIL';